### ISSUE TITLE
Task terminated with unhandled exception

### ISSUE THREAD

**Issue by abbaspalash** [aldacron/LearningD#2]
Hi
Thanks for the code,
But It seems there is a problem in Find Movie(s) action
after two or three times , 

```
Task terminated with unhandled exception: Attempted to access an uninitialized payload.
Program exited with code -11
```

**Comment by mdparker** [comment]
Thanks for reporting this. I've just returned from a long vacation and will look into it soon. Just wanted to let you know that I'm not ignoring you.

**Comment by abbaspalash** [comment]
Thanks

**Comment by mdparker** [comment]
OK. So far I've been unable to reproduce this. Which platform did you see the error on? Does it happen no matter how many movies are int he database? Are you entering the data in English or a different language? Any additional information you can provide may help me narrow it down.

**Comment by Kubic-C** [comment]
i'll guess well never find out
